import { GRID_CONFIG } from "../constants";
const StatusDotRenderer = (props) => {
  const statusColor = props.value ? "green" : "red";

  return (
    <span
      style={{
        display: "inline-block",
        width: "12px",
        height: "12px",
        borderRadius: "50%",
        backgroundColor: statusColor,
        margin: "auto",
      }}
    ></span>
  );
};
export const getColumnDefs = () => [
  {
    field: "firstName",
    headerName: "First Name",
    sortable: true,
    filter: "agTextColumnFilter",
    minWidth: 140,
    tooltipField: "firstName",
    headerTooltip: "Employee first name",
  },
  {
    field: "lastName",
    headerName: "Last Name",
    sortable: true,
    filter: "agTextColumnFilter",
    minWidth: 140,
    tooltipField: "lastName",
    headerTooltip: "Employee last name",
  },
  {
    field: "email",
    headerName: "Email",
    sortable: true,
    filter: "agTextColumnFilter",
    minWidth: 200,
    tooltipField: "email",
    headerTooltip: "Employee email address",
  },
  {
    field: "department",
    headerName: "Department",
    sortable: true,
    filter: "agTextColumnFilter",
    minWidth: 150,
    tooltipField: "department",
    headerTooltip: "Employee department",
    hide: false,
  },
  {
    field: "position",
    headerName: "Position",
    sortable: true,
    filter: "agTextColumnFilter",
    minWidth: 150,
    tooltipField: "position",
    headerTooltip: "Employee job position",
  },
  {
    field: "salary",
    headerName: "Salary",
    sortable: true,
    filter: "agNumberColumnFilter",
    valueFormatter: (p) => `$${p.value.toLocaleString()}`,
    minWidth: 150,
    tooltipField: "salary",
    headerTooltip: "Employee annual salary",
  },
  {
    field: "hireDate",
    headerName: "Hire Date",
    sortable: true,
    filter: "agDateColumnFilter",
    minWidth: 200,
    tooltipField: "hireDate",
    headerTooltip: "Employee hire date",
  },
  {
    field: "age",
    headerName: "Age",
    sortable: true,
    filter: "agNumberColumnFilter",
    minWidth: 120,
    tooltipField: "age",
    headerTooltip: "Employee age in years",
  },
  {
    field: "location",
    headerName: "Location",
    sortable: true,
    filter: "agTextColumnFilter",
    minWidth: 150,
    tooltipField: "location",
    headerTooltip: "Employee work location",
  },
  {
    field: "performanceRating",
    headerName: "Rating",
    sortable: true,
    filter: "agNumberColumnFilter",
    minWidth: 130,
    tooltipField: "performanceRating",
    headerTooltip: "Employee performance rating (1-5)",
    valueFormatter: (params) => `${params.value}/5.0`,
  },
  {
    field: "projectsCompleted",
    headerName: "Projects Completed",
    sortable: true,
    filter: "agNumberColumnFilter",
    minWidth: 175,
    tooltipField: "projectsCompleted",
    headerTooltip: "Number of projects completed",
  },
  {
    field: "isActive",
    headerName: "Active",
    sortable: true,
    filter: "agTextColumnFilter",
    valueFormatter: (params) => (params.value ? "Active" : "Inactive"),
    cellRenderer: StatusDotRenderer,
    width: 100,
    cellStyle: { textAlign: "center" },
    tooltipField: "isActive",
    headerTooltip: "Employee active status",
  },
  {
    field: "skills",
    headerName: "Skills",
    sortable: true,
    filter: "agTextColumnFilter",
    minWidth: 200,
    valueFormatter: (p) => (p.value ? p.value.join(", ") : ""),
    tooltipField: "skills",
    headerTooltip: "Employee technical skills",
    cellStyle: { whiteSpace: "normal", lineHeight: "1.4" },
  },
  {
    field: "manager",
    headerName: "Manager",
    sortable: true,
    filter: "agTextColumnFilter",
    valueFormatter: (p) => p.value ?? "-",
    minWidth: 150,
    tooltipField: "manager",
    headerTooltip: "Employee manager name",
  },
];

export const getDefaultColDef = () => ({
  flex: 1,
  minWidth: 120,
  resizable: true,
  floatingFilter: true,
  sortable: true,
  filter: true,
});

export const getGridOptions = () => ({
  pagination: true,
  paginationPageSize: GRID_CONFIG.DEFAULT_PAGE_SIZE,
  paginationPageSizeSelector: GRID_CONFIG.PAGE_SIZE_OPTIONS,
  rowSelection: { mode: "multiRow", enableClickSelection: true },
  domLayout: "normal",
  defaultColDef: {
    sortable: true,
    resizable: true,
  },
  enableBrowserTooltips: true,
  animateRows: true,
  rowHeight: 50,
  headerHeight: 50,
});
